name: Release

on:
  workflow_dispatch:
    inputs:
      next:
        description: "Version or major (maj), minor (min, feature, feat) or patch (bug, bugfix)"
        required: true

env:
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release "${{ github.event.inputs.next }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 7.4
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v1

      - name: Release
        run: bin/changelog release ${{ github.event.inputs.next }} --target=${{ github.ref }}


